import shirt2 from "./../assets/shirt2.jpg";
import shirt3 from "./../assets/shirt3.jpg";
import pants1 from "./../assets/pants1.jpg";
import pants2 from "./../assets/pants2.jpg";
import pants3 from "./../assets/pants3.jpg";
import shirt1 from "./../assets/shirt1.jpg";
import jacket from "./../assets/jacket-1.webp";

export const data = {
	allProducts: [
    {
      id:1,
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: jacket,
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      size: {id:1, size:"xl"}
    },
    {
      id:2,
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: shirt2,
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      id:3,
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: shirt2,
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      id:4,
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: shirt1,
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      id:5,
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: shirt3,
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      id:6,
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: pants1,
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      id:7,
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: pants2,
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      id:8,
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: pants3,
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
}